export interface DribbleItem {
  id: string;
  type: "image" | "video";
  src: string;
  poster?: string;
  title?: string;
  description?: string;
  hasContent: boolean;
}

export const defaultItems: DribbleItem[] = [
  {
    id: "1",
    type: "image",
    src: "/videos/1.jpg",
    poster: "/videos/1.jpg",
    title: "Luxury Fashion Campaign",
    description: "High-end editorial photography showcasing the new summer collection.",
    hasContent: true,
  },
  {
    id: "2",
    type: "video",
    src: "/videos/18.mp4",
    poster: "/videos/18.mp4",
    title: "Interactive Web Experience",
    description: "Smooth transitions and engaging animations for modern web interfaces.",
    hasContent: true,
  },
  {
    id: "3",
    type: "image",
    src: "/videos/2.jpg",
    poster: "/videos/2.jpg",
    title: "Editorial Design Series",
    description: "Bold typography and minimalist layouts for contemporary publications.",
    hasContent: true,
  },
  {
    id: "4",
    type: "video",
    src: "/videos/19.mp4",
    poster: "/videos/19.mp4",
    title: "Motion Graphics Showcase",
    description: "Dynamic visual storytelling through fluid animations and kinetic typography.",
    hasContent: true,
  },
  {
    id: "5",
    type: "image",
    src: "/videos/3.jpg",
    poster: "/videos/3.jpg",
    title: "Visual Identity Lab",
    description: "Material-driven identity systems—palette, type, textures, and signature.",
    hasContent: true,
  },
  {
    id: "6",
    type: "video",
    src: "/videos/20.mp4",
    poster: "/videos/20.mp4",
    title: "Modular Framer Websites",
    description: "Component-driven builds with responsive grids and subtle motion.",
    hasContent: true,
  },
  {
    id: "7",
    type: "image",
    src: "/videos/4.jpg",
    poster: "/videos/4.jpg",
    title: "Promotional creative for luxury perfume brand",
    description: "An immersive luxury scene showcasing product sophistication with nature",
    hasContent: true,
  },
  {
    id: "8",
    type: "video",
    src: "/videos/21.mp4",
    poster: "/videos/21.mp4",
    title: "Modular Framer Websites",
    description: "Component-driven builds with responsive grids and subtle motion.",
    hasContent: true,
  },
  {
    id: "9",
    type: "image",
    src: "/videos/5.jpg",
    poster: "/videos/5.jpg",
    title: "Premium Product Photography",
    description: "Studio-quality compositions highlighting form, texture, and craftsmanship.",
    hasContent: true,
  },
  {
    id: "10",
    type: "video",
    src: "/videos/22.mp4",
    poster: "/videos/22.mp4",
    title: "UI/UX Animation Demo",
    description: "Micro-interactions and seamless transitions for enhanced user experience.",
    hasContent: true,
  },
  {
    id: "11",
    type: "image",
    src: "/videos/6.jpg",
    poster: "/videos/6.jpg",
    title: "Brand Identity Design",
    description: "Cohesive visual systems that capture brand essence and values.",
    hasContent: true,
  },
  {
    id: "12",
    type: "video",
    src: "/videos/23.mp4",
    poster: "/videos/23.mp4",
    title: "Digital Product Launch",
    description: "Engaging reveal animations and interactive elements for product showcases.",
    hasContent: true,
    
  },
  {
    id: "13",
    type: "image",
    src: "/videos/7.jpg",
    poster: "/videos/7.jpg",
    title: "Creative Campaign Artwork",
    description: "Eye-catching visuals designed to inspire and engage audiences.",
    hasContent: true,
  },
  {
    id: "14",
    type: "image",
    src: "/videos/8.jpg",
    poster: "/videos/8.jpg",
    title: "Architectural Visualization",
    description: "Photorealistic renders showcasing spatial design and material detail.",
    hasContent: true,
  },
  {
    id: "15",
    type: "image",
    src: "/videos/9.jpg",
    poster: "/videos/9.jpg",
    title: "Abstract Art Direction",
    description: "Experimental compositions exploring color, form, and visual rhythm.",
    hasContent: true,
  },
  {
    id: "16",
    type: "image",
    src: "/videos/10.jpg",
    poster: "/videos/10.jpg",
    title: "Lifestyle Photography",
    description: "Authentic moments captured with natural lighting and composition.",
    hasContent: true,
  },
  {
    id: "17",
    type: "image",
    src: "/videos/11.jpg",
    poster: "/videos/11.jpg",
    title: "Conceptual Illustration",
    description: "Narrative-driven imagery blending traditional and digital techniques.",
    hasContent: true,
  },
  {
    id: "18",
    type: "image",
    src: "/videos/12.jpg",
    poster: "/videos/12.jpg",
    title: "Package Design System",
    description: "Sustainable packaging solutions with striking shelf presence.",
    hasContent: true,
  },
  {
    id: "19",
    type: "image",
    src: "/videos/13.jpg",
    poster: "/videos/13.jpg",
    title: "Digital Art Installation",
    description: "Immersive experiences combining projection mapping and interaction.",
    hasContent: true,
  },
  {
    id: "20",
    type: "image",
    src: "/videos/14.jpg",
    poster: "/videos/14.jpg",
    title: "Typography Exploration",
    description: "Custom lettering and type treatments for unique brand voices.",
    hasContent: true,
  },
  {
    id: "21",
    type: "image",
    src: "/videos/15.jpg",
    poster: "/videos/15.jpg",
    title: "Social Media Campaign",
    description: "Scroll-stopping content optimized for engagement and reach.",
    hasContent: true,
  },
  {
    id: "22",
    type: "image",
    src: "/videos/16.jpg",
    poster: "/videos/16.jpg",
    title: "Seafood Concept Creative",
    description: "A visually rich concept that elevates a simple dish into an expressive narrative.",
    hasContent: true,
  },
  {
    id: "23",
    type: "image",
    src: "/videos/17.jpg",
    poster: "/videos/17.jpg",
    title: "Foam Serum Launch",
    description: "Bubbly physics + product CGI used across hero, ads, and socials.",
    hasContent: true,
  },
  {
    id: "24",
    type: "image",
    src: "/videos/24.jpg",
    poster: "/videos/24.jpg",
    title: "Visual Identity Lab",
    description: "Material-driven identity systems—palette, type, textures, and signature.",
    hasContent: true,
  },
];
