export interface DribbleItem {
  id: string;
  type: "image" | "video";
  src: string;
  poster?: string;
  title?: string;
  description?: string;
  hasContent: boolean;
}

export const defaultItems: DribbleItem[] = [
  {
    id: "1",
    type: "image",
    src: "/videos/1.jpg",
    poster: "/videos/1.jpg",
    title: "lorel ipsum dolor sit amet",
    description: "lorel ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
    hasContent: true,
  },
  {
    id: "2",
    type: "video",
    src: "/videos/28.mp4",
    poster: "/videos/28.mp4",
    title: "Modular Framer Websites",
    description: "Component-driven builds with responsive grids and subtle motion.",
    hasContent: true,
  },
  {
    id: "3",
    type: "image",
    src: "/videos/3.jpg",
    poster: "/videos/3.jpg",
    title: "Covers",
    description: "We delivered over 250 editorial designs this year",
    hasContent: true,
  },
  {
    id: "4",
    type: "video",
    src: "/videos/27.mp4",
    poster: "/videos/27.mp4",
    title: "Modular Framer Websites",
    description: "Component-driven builds with responsive grids and subtle motion.",
    hasContent: true,
  },
  {
    id: "5",
    type: "image",
    src: "/videos/5.jpg",
    poster: "/videos/5.jpg",
    title: "Visual Identity Lab",
    description: "Material-driven identity systems—palette, type, textures, and signature.",
    hasContent: true,
  },
  {
    id: "6",
    type: "video",
    src: "/videos/26.mp4",
    poster: "/videos/26.mp4",
    title: "Modular Framer Websites",
    description: "Component-driven builds with responsive grids and subtle motion.",
    hasContent: true,
  },
  {
    id: "7",
    type: "image",
    src: "/videos/7.jpg",
    poster: "/videos/7.jpg",
    title: "Promotional creative for luxury perfume brand",
    description: "An immersive luxury scene showcasing product sophistication with nature",
    hasContent: true,
  },
  {
    id: "8",
    type: "video",
    src: "/videos/22.mp4",
    poster: "/videos/22.mp4",
    title: "Modular Framer Websites",
    description: "Component-driven builds with responsive grids and subtle motion.",
    hasContent: true,
  },
  {
    id: "9",
    type: "image",
    src: "/videos/9.jpg",
    poster: "/videos/9.jpg",
    title: "Modular Framer Websites",
    description: "Component-driven builds with responsive grids and subtle motion.",
    hasContent: true,
  },
  {
    id: "10",
    type: "video",
    src: "/videos/21.mp4",
    poster: "/videos/21.mp4",
    title: "Modular Framer Websites",
    description: "Component-driven builds with responsive grids and subtle motion.",
    hasContent: true,
  },
  {
    id: "11",
    type: "image",
    src: "/videos/11.jpg",
    poster: "/videos/11.jpg",
    title: "Modular Framer Websites",
    description: "Component-driven builds with responsive grids and subtle motion.",
    hasContent: true,
  },
  {
    id: "12",
    type: "video",
    src: "/videos/18.mp4",
    poster: "/videos/18.mp4",
    title: "Modular Framer Websites",
    description: "Component-driven builds with responsive grids and subtle motion.",
    hasContent: true,
    
  },
  {
    id: "13",
    type: "image",
    src: "/videos/13.jpg",
    poster: "/videos/13.jpg",
    title: "Modular Framer Websites",
    description: "Component-driven builds with responsive grids and subtle motion.",
    hasContent: true,
  },
  {
    id: "14",
    type: "image",
    src: "/videos/14.jpg",
    poster: "/videos/14.jpg",
    title: "Modular Framer Websites",
    description: "Component-driven builds with responsive grids and subtle motion.",
    hasContent: true,
  },
  {
    id: "15",
    type: "image",
    src: "/videos/15.jpg",
    poster: "/videos/15.jpg",
    title: "Modular Framer Websites",
    description: "Component-driven builds with responsive grids and subtle motion.",
    hasContent: true,
  },
  {
    id: "16",
    type: "image",
    src: "/videos/16.jpg",
    poster: "/videos/16.jpg",
    title: "Modular Framer Websites",
    description: "Component-driven builds with responsive grids and subtle motion.",
    hasContent: true,
  },
  {
    id: "17",
    type: "image",
    src: "/videos/17.jpg",
    poster: "/videos/17.jpg",
    title: "Modular Framer Websites",
    description: "Component-driven builds with responsive grids and subtle motion.",
    hasContent: true,
  },
  {
    id: "18",
    type: "image",
    src: "/videos/24.jpg",
    poster: "/videos/24.jpg",
    title: "Modular Framer Websites",
    description: "Component-driven builds with responsive grids and subtle motion.",
    hasContent: true,
  },
  {
    id: "19",
    type: "image",
    src: "/videos/12.jpg",
    poster: "/videos/12.jpg",
    title: "Modular Framer Websites",
    description: "Component-driven builds with responsive grids and subtle motion.",
    hasContent: true,
  },
  {
    id: "20",
    type: "image",
    src: "/videos/10.jpg",
    poster: "/videos/10.jpg",
    title: "Modular Framer Websites",
    description: "Component-driven builds with responsive grids and subtle motion.",
    hasContent: true,
  },
  {
    id: "21",
    type: "image",
    src: "/videos/8.jpg",
    poster: "/videos/8.jpg",
    title: "Modular Framer Websites",
    description: "Component-driven builds with responsive grids and subtle motion.",
    hasContent: true,
  },
  {
    id: "22",
    type: "image",
    src: "/videos/6.jpg",
    poster: "/videos/6.jpg",
    title: "Seafood Concept Creative",
    description: "A visually rich concept that elevates a simple dish into an expressive narrative.",
    hasContent: true,
  },
  {
    id: "23",
    type: "image",
    src: "/videos/4.jpg",
    poster: "/videos/4.jpg",
    title: "Foam Serum Launch",
    description: "Bubbly physics + product CGI used across hero, ads, and socials.",
    hasContent: true,
  },
  {
    id: "24",
    type: "image",
    src: "/videos/2.jpg",
    poster: "/videos/2.jpg",
    title: "Visual Identity Lab",
    description: "Material-driven identity systems—palette, type, textures, and signature.",
    hasContent: true,
  },
];
